[package]
name = 'IntegerMate'
version = '1.0.0'

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
integer_mate = "0xc3a610069fa7545cf14e266e849954bf385aca957bb489b1dc069a4baa29b502"

[dependencies.AptosTokenObjects]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/aptos-token-objects"
